---
name: Release
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release:
    needs: [test]
    uses: tigattack/repo_utils/.github/workflows/ansible-role-publish.yml@main
    with:
      role_name: ${{ needs.test.outputs.role_name }}
    secrets:
      op_service_account_key: ${{ secrets.OP_SERVICE_ACCOUNT_KEY }}
